codecov:
  token: e31d94e4-2b13-4ab2-89f8-87f861c54316

comment: off
# show coverage in CI status, but never consider it a failure
coverage:
  status:
    project:
      default:
        target: 0%
    patch:
      default:
        target: 0%
